name: Release (build + publish + attach)

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          pwd
          ls -la
          echo "---- .github/workflows ----"
          ls -la .github/workflows || true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Install a Gradle CLI so we can run `gradle ...` (no wrapper needed)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      # If your project is not in the repo root, set this to that folder (e.g. project/)
      - name: Build
        run: gradle build
        # working-directory: .

      - name: Publish to GitHub Packages (Maven)
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle publish --stacktrace
        # working-directory: .

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*-sources.jar
            build/libs/*-javadoc.jar
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # If your build is in a subfolder, change the paths above or add `working-directory: <subdir>`
