name: Release (build + publish + attach)

on:
  release:
    types: [published]  # run when a release is published

permissions:
  contents: write        # needed to attach assets
  packages: write        # needed to publish to gh packages

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Publish to GitHub Packages (Maven)
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --stacktrace

      # Attach built jars to the GitHub Release page
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*-sources.jar
            build/libs/*-javadoc.jar
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
